var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                              x                                              x  ",
   "                        xx    x           xxxxxxxxxx             x           x  ",
   "  x                xx         x                    x xx   xxxxxxx            x  ",
   "  x             xx            x    xxxxxr          x    x               r x  x  ",
   "  x          xxx              x             x           x                 x  x  ",
   "  x  @     x                  x             x           x        xxxxx    x ox  ",
   "  xxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                o                 ",
   "             xx   r   xx    r   x   x    xx    x  r xx               x   x   x               xxxxxx               ",
   "     @       x         x        x   x          x     x      xx       x   x!!!x     r         x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "             x         x       xx   x          x     x               x           x x         x                    ",
   "!!!!!!!!!!!!!x!!!!!!!!!x!!!!!!xx!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!x           x x         x                    ",
   "!!!!!!!!!!!!!x!!!!!!!!!x!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx xx       xx                    ",
   "!!!!!!!!!!!!!x!!!!!!!!!x!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx                     ",],
  ["                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                             x xxx x x xxx x                               ",
   "                             x              x                              ",
   "   @                          xx            x                              ",
   "  xxx                         x     xx      x                              ",
   "  x x                         x    x!!x    x                               ",
   "  x                           x     xx    x                                ",
   "  x                                                                        ",
   "  x                                        r                               ",
   "  x                                                   o                    ",
   "  x                 x      r              x       xxxxxxxxx                ",
   "  x                 x         xx          x                                ",
   "  x                 x         x    xxx    x                                ",
   "  x                 x         xxxxxxxxxxxxx                                ",
   "  x                 x         x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                           ",
   "                                                                           "],
  ["  x     x         xxxxx      x      x                                      ",
   "   x   x         x      x    x      x                                      ",
   "    x x          x      x    x      x                                      ",
   "     x           x     x     x      x                                      ",
   "x		 x             xxxx      xxxxxxxx                                      ",
   "x                                                                          ",
   "x                                                                          ",
   "x              x             x    x     x   xx      x                      ",
   "x               x           x     x     x   x  x    x                      ",
   "                 x   x x   x      x     x   x    x  x                      ",
   "                  x x   x x       x     x   x     x x                      ",
   "x@                                                                o x      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                           "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
